### PR TITLE
Pull request support, fixed tests

### PR DESCRIPTION
**Pull request by sirtoobii**
- Fixed my broken tests - sorry
- Added support for pull requests
- Fixed circleCI workflow_id

image

### CODE REVIEW

**Review by oetiker — APPROVED** [review]

**Comment by oetiker** [comment]
du flickst gleich die anderen CIs mit :) cool

**Comment by sirtoobii** [comment]
hej @kan any chances to get this as a new release? (I can also help if you add me as co-maintainer on pause)

**Comment by kan** [comment]
@sirtoobii 
Sorry, in the next few days I'm going to release a new version.
Let me think a bit about giving PAUSE co-maintainer. 😃

**Comment by kan** [comment]
@sirtoobii 
Thank you for your patience. I've released 0.31 to CPAN and it should be available soon.

**Pull request merged**
